version: '3.8'

services:
  # Serviço da API (Back-end FastAPI)
  api:
    build: . # Constrói a imagem a partir do Dockerfile na pasta atual
    container_name: selo_fiea_api
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app # Monta o código local para live reload
    ports:
      - "8000:8000"
    env_file:
      - ./.env # Carrega variáveis de ambiente de um arquivo .env
    depends_on:
      - db
      - redis

  # Serviço de Banco de Dados
  db:
    image: postgres:14-alpine
    container_name: selo_fiea_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./.env

  # Serviço de Cache e Fila
  redis:
    image: redis:7-alpine
    container_name: selo_fiea_redis
    ports:
      - "6379:6379"

  # Serviço de Armazenamento de Objetos S3-compatível
  minio:
    image: minio/minio:latest
    container_name: selo_fiea_minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000" # Porta da API do MinIO
      - "9001:9001" # Porta do Console Web
    env_file:
      - ./.env
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data: